#pragma once

/* Generated by gen_kconfig.py - do not edit. */
/* kernel source path: /src/out-star-bbr-fq-llvm23-20260923 */
/* compiler: clang */
/* probes passed: 21/47 */

/* #undef TCP_CONGESTION_OPS_CONG_CONTROL_HAS_4_ARGS (not available) */
/* #undef TCP_CONGESTION_OPS_HAS_TSO_SEGS (not available) */
/* #undef TCP_CONGESTION_OPS_HAS_SKB_MARKED_LOST (not available) */
#define HAVE_TCP_ECN_OK 1
/* #undef HAVE_TCP_ECN_LOW (not available) */
/* #undef HAVE_TCP_ECN_ECT_PERMANENT (not available) */
#define HAVE_TCP_CONG_NEEDS_ECN 1
/* #undef HAVE_TCP_CONG_WANTS_CE_EVENTS (not available) */
/* #undef HAVE_CA_EVENT_TLP_RECOVERY (not available) */
#define HAVE_CA_EVENT_ECN_IS_CE 1
/* #undef HAVE_RATE_SAMPLE_LOST (not available) */
#define HAVE_RATE_SAMPLE_LOSSES 1
/* #undef HAVE_RATE_SAMPLE_TX_IN_FLIGHT (not available) */
#define HAVE_RATE_SAMPLE_PRIOR_IN_FLIGHT 1
/* #undef HAVE_RATE_SAMPLE_IS_ACKING_TLP_RETRANS_SEQ (not available) */
/* #undef HAVE_RATE_SAMPLE_IS_ECE (not available) */
/* #undef HAVE_RATE_SAMPLE_DELIVERED_CE (not available) */
#define HAVE_TCP_SOCK_DELIVERED_CE 1
/* #undef HAVE_TCP_SOCK_FAST_ACK_MODE (not available) */
/* #undef HAVE_TCP_SOCK_TLP_ORIG_DATA_APP_LIMITED (not available) */
#define HAVE_TCP_SOCK_IS_SACK_RENEG 1
#define HAVE_TCP_SOCK_LOST 1
#define HAVE_TCP_SOCK_LOST_OUT 1
#define HAVE_TCP_SOCK_PRIOR_CWND 1
#define HAVE_TCP_SOCK_TCP_CLOCK_CACHE 1
#define HAVE_TCP_SOCK_ECN_FLAGS 1
#define HAVE_TCP_SOCK_SND_CWND 1
#define HAVE_SKB_CB_TX_IN_FLIGHT 1
/* #undef HAVE_SKB_CB_TX_LOST (not available) */
#define HAVE_SKB_CB_TX_DELIVERED_MSTAMP 1
#define HAVE_SKB_CB_TX_IS_APP_LIMITED 1
/* #undef HAVE_TCP_SND_CWND (not available) */
/* #undef HAVE_TCP_SND_CWND_SET (not available) */
#define HAVE_TCP_STAMP_US_DELTA 1
#define HAVE_TCP_MIN_RTT 1
#define HAVE___TCP_SEND_ACK 1
/* #undef HAVE_GET_RANDOM_U32_BELOW (not available) */
#define HAVE_PRANDOM_U32_MAX 1
/* #undef HAVE_TCP_PLB_STATE (not available) */
/* #undef HAVE_TCP_PLB_SCALE (not available) */
/* #undef HAVE_TCP_PLB_UPDATE_STATE (not available) */
/* #undef HAVE_TCP_PLB_CHECK_REHASH (not available) */
/* #undef HAVE_TCP_PLB_UPDATE_STATE_UPON_RTO (not available) */
/* #undef HAVE_SYSCTL_TCP_PLB_ENABLED (not available) */
/* #undef HAVE_TCP_BBR_PHASE (not available) */
/* #undef HAVE_TCP_BBR_INFO_V2 (not available) */
#define HAVE_ICSK_CA_PRIV 1
